// <auto-generated />
using System;
using ERPServices.ReportCashFlow.API.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPServices.Report.API.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ERPServices.ReportCashFlow.API.Model.CashFlowDailyReportEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_inc");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_credit");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_debit");

                    b.HasKey("Id");

                    b.ToTable("cash_flow_daily_report");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Date = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalCredit = 100m,
                            TotalDebit = 200m
                        },
                        new
                        {
                            Id = 2L,
                            Date = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalCredit = 140m,
                            TotalDebit = 210m
                        },
                        new
                        {
                            Id = 3L,
                            Date = new DateTime(2022, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalCredit = 1000m,
                            TotalDebit = 2000m
                        },
                        new
                        {
                            Id = 4L,
                            Date = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalCredit = 160m,
                            TotalDebit = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
